name: Test Build Openwrt Stable

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get-version:
    name: get latest version number
    runs-on: ubuntu-latest
    outputs:
      CUR_VERSION: ${{steps.get-version.outputs.CUR_VERSION}}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: VERSION_CONTROL
        fetch-depth: 1
        path: version_control
    - name: get version
      id: get-version
      run: |
          #获取当前版本号
          pre_version=$(cat version_control/VERSION | grep "PREFEX" | sed 's/PREFEX=\(.*\)/\1/')
          cur_version=$(cat version_control/VERSION | grep "CUR_VERS" | sed 's/CUR_VERS=\(.*\)/\1/')
          echo "CUR_VERSION=$pre_version$cur_version" >> $GITHUB_OUTPUT
          
  release:
    name: Build for ${{ matrix.arch }}
    needs: get-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.0/targets/mediatek/filogic
            sdk_name: -sdk-24.10.0-mediatek-filogic_
          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.0/targets/x86/64
            sdk_name: -sdk-24.10.0-x86-64_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache
      OPENWRT_RELEASE: 24.10.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:cache:
      - name: Setup CCache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:release:ccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:ccache:
      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc
      - name: Prepare For Build
        run: |
          sdk_home="$(mktemp -d)"
          test -d ~/.ccache || mkdir -p ~/.ccache
          ln -sf ~/.ccache "$sdk_home/.ccache"
          echo "SDK_HOME=$sdk_home" >> $GITHUB_ENV
          echo "CONFIG_CCACHE=y" >> $GITHUB_ENV
          #修改版本号
          sed -i "s/VER=.*/VER=${{needs.get-version.outputs.CUR_VERSION}}/" ${{ github.workspace }}/package/openwrt/make_openwrt.sh         
      - name: Build package
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: sh ${{ github.workspace }}/package/openwrt/make_openwrt.sh

      - name: Show CCache Status
        run: |
          eval "${{ env.SDK_HOME }}/staging_dir/host/bin/ccache -s"

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=${{needs.get-version.outputs.CUR_VERSION}}-OpenWrt" >> $GITHUB_OUTPUT
          touch release.txt
          echo "同步更新上游代码" >> release.txt
          echo ${{ github.sha }} >> Release.txt
          echo "status=success" >> $GITHUB_OUTPUT
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          # do not use GITHUB_TOKEN
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ github.workspace }}/package/openwrt/smartdns*.ipk
